csedu/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
import home.urls
from django.conf.urls.i18n import i18n_patterns
import identity.urls

urlpatterns = i18n_patterns(
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include(home.urls, namespace='home')),
)

urlpatterns += [
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^identity/', include(identity.urls, namespace='identity')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.conf.urls import url
from django.utils.translation import ugettext_lazy as _
import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^about/$', views.about, name='about'),
    url(r'^people/$', views.people, name='people'),
    url(r'^profile/(?P<id>.+?)/(?P<first_name>.+?)-(?P<last_name>.+?)/$',
        views.profile, name='profile'),
    url(r'^program-overview/$', views.programs_overview,
        name='programOverview'),
    url(r'^research/$', views.research, name='research'),
    url(r'^news-events-overview/$',
        views.news_events_overview, name='newsEventsOVerview'),
    url(r'^news-event/(?P<id>.+?)/$', views.news_event, name='newsEvent'),
    url(r'^research-group/$', views.research_group, name='researchGroup'),
    # url(_(r'^industrial-relations/$'),
    #     views.industrial_relations, name='industrial')
]

identity/urls.py
from django.conf.urls import url
import views

urlpatterns = [
    url(r'^login/$', views.login_redirect, name='login'),
    url(r'^authenticate-user/$', views.authenticate_user, name='authenticate'),
]

home/models.py
from django.shortcuts import get_object_or_404
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Q
from datetime import date
from django.db.models.functions import Substr
from itertools import groupby
from operator import itemgetter
from random import shuffle
import locale


class FacultyMember(models.Model):
    first_name = models.CharField(max_length=50)
    middle_name = models.CharField(max_length=50, blank=True)
    last_name = models.CharField(max_length=60)
    title = models.CharField(max_length=60)
    phd = models.CharField(max_length=90)
    interest = models.TextField()
    email = models.EmailField()
    is_active = models.BooleanField()
    office = models.CharField(max_length=90)
    phone = models.CharField(max_length=50)
    bio = models.TextField()
    website = models.CharField(max_length=90, blank=True)
    chair = models.BooleanField()
    vice_chair = models.BooleanField()
    image = models.ImageField(blank=True, upload_to="img/profile")
    leave = models.BooleanField()
    visit = models.BooleanField()
    twitter = models.CharField(max_length=150, blank=True)
    linkedin = models.CharField(max_length=150, blank=True)
    google_scholar = models.CharField(max_length=150, blank=True)
    DBLP = models.CharField(max_length=150, blank=True)
    CV = models.FileField(upload_to="cvs", blank=True)

    def __unicode__(self):
        return self.first_name + ' ' + self.last_name

    @staticmethod
    def overview_by_three():
        # this extra sort line for turkish character issue
        locale.setlocale(locale.LC_ALL, "")
        faculty = list(FacultyMember.objects.filter(
            is_active=True).order_by('last_name').values(
            'id', 'first_name', 'middle_name', 'email', 'leave', 'last_name',
            'image', 'title', 'phd', 'interest', 'visit', 'chair').all())
        # this extra sort line for turkish character issue
        faculty = sorted(faculty, key=lambda x: x['last_name'],
                         cmp=locale.strcoll)
        return list_by_three(faculty)

    @staticmethod
    def by_fix_three():
        faculty = list(FacultyMember.objects.filter(
            is_active=True).order_by('last_name')
            .values('id', 'first_name', 'middle_name', 'email',
                    'leave', 'last_name', 'image', 'title',
                    'phd', 'interest', 'visit', 'chair').all())
        shuffle(faculty)
        return list_by_three(fix_to_three(faculty))

    @staticmethod
    def get_profile_information(id, first_name, last_name):
        return get_object_or_404(FacultyMember.objects.filter(
            pk=id,
            first_name=first_name,
            last_name=last_name
        ))

    @staticmethod
    def get_publications_grouped_by_year(faculty):
        pubs = faculty.publication_set.all()
        groubed_pubs = dict()
        for i in pubs:
            if i.year in groubed_pubs:
                groubed_pubs[i.year].append(i)
            else:
                groubed_pubs[i.year] = [i]
        return sorted(groubed_pubs.items(),
                      reverse=True,
                      key=lambda k: k[0])

    @staticmethod
    def get_publications_grouped_by_type(faculty):
        return {k: list(v) for k, v in
                groupby(faculty.publication_set.order_by('-type_of').all(),
                        lambda x: str(x.type_of))}


class Publication(models.Model):
    info = models.TextField()
    year = models.IntegerField()
    type_of = models.CharField(max_length=40)
    # Thanks to myself perfect spelling
    # correct that and migrate database
    citetion_count = models.IntegerField(default=0, null=True, blank=True)
    citetion_link = models.CharField(max_length='1000', blank=True)
    # end of thanks
    fetched_from_google_scholar = models.BooleanField(default=False)
    fetched_from_DBLP = models.BooleanField(default=False)
    author = models.ManyToManyField(FacultyMember, blank=True)

    def __unicode__(self):
        return self.info


class Project(models.Model):
    title = models.CharField(max_length=250)
    abstract = models.TextField()
    start_date = models.DateField()
    end_date = models.DateField()
    budget = models.CharField(max_length=100)
    funding_institution = models.CharField(max_length=100)
    website = models.CharField(max_length=90, blank=True)
    poster = models.ImageField(blank=True, upload_to="img/project")
    in_spot_light = models.BooleanField()
    principal_investigator = models.ForeignKey(
        FacultyMember, related_name='investigator')
    researchers = models.ManyToManyField(FacultyMember, blank=True)

    def __unicode__(self):
        return self.title

    @staticmethod
    def get_project_in_slider():
        return Project.objects.filter(
            Q(in_spot_light=True) & Q(end_date__gt=date.today())
        ).order_by('-start_date').annotate(
            short_abstract=Substr('abstract', 1, 300)).values(
            'short_abstract', 'poster')

    @staticmethod
    def get_all_project_by_type():
        return {
            'ongoing': Project.objects.filter(
                end_date__gt=date.today()).order_by(
                '-start_date').select_related('principal_investigator'),
            'completed': Project.objects.filter(
                end_date__lt=date.today()).order_by(
                '-start_date').select_related('principal_investigator'),
        }


class ResearchGroup(models.Model):
    name = models.CharField(max_length=120)
    website = models.CharField(max_length=120, blank=True)
    logo = models.ImageField(blank=True, upload_to="img/logo")
    members = models.ManyToManyField(FacultyMember, blank=True)

    def __unicode__(self):
        return self.name


class NewsEvent(models.Model):
    title = models.CharField(max_length=250)
    date = models.DateField()
    link = models.CharField(max_length=250, blank=True)
    description = models.TextField()
    poster = models.ImageField(blank=True, upload_to="img/news")

    def __unicode__(self):
        return self.title

    @staticmethod
    def get_last_six_by_three():
        return list_by_three(
            NewsEvent.objects.order_by('-date').values(
                'id', 'title', 'description', 'poster', 'date')[:6]
        )

    @staticmethod
    def overview_by_three():
        return list_by_three(
            NewsEvent.objects.order_by('-date').values(
                'id', 'title', 'description', 'poster', 'date'))


class Program(models.Model):
    title = models.CharField(max_length=50)
    type_of = models.CharField(max_length=50, blank=True)
    image = models.ImageField(blank=True, upload_to="img/programs")

    def __unicode__(self):
        return self.title


class ProgramSubField(models.Model):
    title = models.CharField(max_length=50)
    text = models.TextField()
    program = models.ForeignKey(Program, related_name='sub_set')

    def __unicode__(self):
        return self.title


class OtherText(models.Model):
    title = models.CharField(max_length=250)
    text = models.TextField()

    def __unicode__(self):
        return self.title


class IndustrialRelations(models.Model):
    name = models.CharField(max_length=250)
    website = models.CharField(max_length=120, blank=True)
    logo = models.ImageField(blank=True, upload_to="img/industrial")

    def __unicode__(self):
        return self.name

    @staticmethod
    def by_tree():
        return list_by_three(IndustrialRelations.objects.all())


# TODO: Put that function to better place


def list_by_three(li):
    three = []
    n_three = 0
    for i in range(len(li)):
        if i / 3 == n_three:
            three.append(list())
            n_three += 1
        three[i / 3].append(li[i])
    return three

# TODO: Hey me. You can do that with javascript when you don't feel lazy


def fix_to_three(li):
    if len(li) % 3 is not 0:
        li = li * 3
    return li


def to_three_col(li):
    div_num = (len(li) / 3)
    if len(li) % 3 == 1:
        div_num += 1
        return [
            li[0:div_num],
            li[div_num:(2 * div_num) - 1], li[(2 * div_num) - 1:]]
    elif len(li) % 3 == 2:
        div_num += 1
        return [li[0:div_num], li[div_num:2 * div_num], li[2 * div_num:]]
    return [li[0:div_num], li[div_num:2 * div_num], li[2 * div_num:]]

home/forms.py
from home.models import *
from django import forms

TITLE_CHOICES = (
    ("Professor", "Professor"),
    ("Associate Professor", "Associate Professor"),
    ("Assistant Professor", "Assistant Professor"),
)

YES_OR_NO = (
    (True, 'Yes'),
    (False, 'No')
)

PUBLICATION_CHOICES = (
    ("Journal Paper", "Journal Paper"),
    ("Conference - Workshop Paper", "Conference - Workshop Paper"),
    ("Book", "Book"),
    ("Book Chapter", "Book Chapter"),
    ("Patent", "Patent"),
    ("Research Poster", "Research Poster"),
)

PROGRAM_TYPES_CHOICES = (('Graduate', 'Graduate'),
                         ('Undergraduate', 'Undergraduate'))


class FacultyMemberForm(forms.ModelForm):
    title = forms.ChoiceField(choices=TITLE_CHOICES)
    chair = forms.ChoiceField(choices=YES_OR_NO,
                              label='Are you department chair?',
                              initial=False)

    vice_chair = forms.ChoiceField(choices=YES_OR_NO,
                                   label='Are you department vice chair?',
                                   initial=False)

    leave = forms.ChoiceField(choices=YES_OR_NO,
                              label='Are you on leave?',
                              initial=False)

    visit = forms.ChoiceField(choices=YES_OR_NO,
                              label='Are you a visiting faculty member?',
                              initial=False)

    class Meta:
        model = FacultyMember
        exclude = []


class PublicationForm(forms.ModelForm):
    type_of = forms.ChoiceField(choices=PUBLICATION_CHOICES,
                                label='Type',
                                initial=False)

    class Meta:
        model = Publication
        exclude = ['fetched_from_google_scholar', 'fetched_from_DBLP']


class ProgramForm(forms.ModelForm):
    type_of = forms.ChoiceField(choices=PROGRAM_TYPES_CHOICES,
                                label='Type',
                                initial=False)

    class Meta:
        model = Program
        exclude = []

home/views.py
from django.shortcuts import render, get_object_or_404
from home.models import *
from counter import Countur


def index(request):
    return render(request, 'index.html',
                  {
                      'slider': Project.get_project_in_slider(),
                      'faculty': FacultyMember.by_fix_three(),
                      'news': NewsEvent.get_last_six_by_three(),
                      'numbers': OtherText.objects.get(title='cs in numbers'),
                      'program': Program.objects.all()
                  })


def about(request):
    return render(request, 'about.html', {
        'other': OtherText.objects.get(title='About')
    })


def people(request):
    return render(request, 'people.html', {
        'faculty': FacultyMember.overview_by_three()
    })


def profile(request, id, first_name, last_name):
    faculty = FacultyMember.get_profile_information(id, first_name, last_name)
    return render(request, 'profile.html', {
        'faculty': faculty,
        'inves_projects': faculty.investigator.order_by('-end_date').all(),
        'research_projects': faculty.project_set.order_by('-end_date').all(),
        'flat_pub': faculty.publication_set.order_by('-year').all(),
        'citetion_pub': faculty.publication_set.order_by(
            '-citetion_count').all(),
        'year_pub': FacultyMember.get_publications_grouped_by_year(faculty),
        'type_pub': FacultyMember.get_publications_grouped_by_type(faculty),
        'counter': Countur()
    })


def programs_overview(request):
    return render(request, 'programsOverview.html', {
        'graduate': Program.objects.filter(type_of="Graduate").all(),
        'undergraduate': Program.objects.filter(type_of="Undergraduate").all()
    })


def research(request):
    return render(request, 'research.html', Project.get_all_project_by_type())


def research_group(request):
    return render(request, 'researchGroup.html', {
        'group': ResearchGroup.objects.order_by('name').all()
    })


def news_events_overview(request):
    return render(request, 'newsEventsOverview.html', {
        'news': NewsEvent.overview_by_three()
    })


def news_event(request, id):
    return render(request, 'newsEvent.html', {
        'news': get_object_or_404(NewsEvent, id=id)
    })


def industrial_relations(request):
    return render(request, 'industrial.html', {
        'industrial': IndustrialRelations.by_tree()
    })

home/templates/about.html
{% extends 'base.html' %} {% load i18n %}

{% block title %}
  {% trans "About" %}
{% endblock %}

{% block content %}
<section>
  <div class="container">
    <div class="box first">
      <div class="center">
        <h3>{% trans other.title %}</h3>
        <div>
          <img src="/static/home/img/about.png" class="img-thumbnail img-responsive small-gap">
        </div>
      </div>
      <!--/.center-->
      {{ other.text|safe }}
    </div>
    <!--/.box-->
  </div>
  <!--/.container-->
</section>
<!--/#portfolio-->
{% endblock %}

home/templates/base.html
<!DOCTYPE html>
<html lang="en">
  {% load i18n %}
  {% load without_lan %}

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="/static/home/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/home/css/font-awesome.min.css" rel="stylesheet">
    <link href="/static/home/css/prettyPhoto.css" rel="stylesheet">
    <link href="/static/home/css/main.css" rel="stylesheet">
    <title>{% block title %}
      {% endblock %}
      -
      {% trans "Computer Science" %}
      -
      {% trans "Istanbul Sehir University" %}</title>
  </head>

  <body data-spy="scroll" data-target="#navbar" data-offset="0">
    <header id="header" role="banner">
      <div class="container" id="language">
        <div class="box">
          <div class="row">
            <div class="col-md-12">
              <div id="">
                <form action="{% url 'set_language' %}" method="post">{% csrf_token %}
                  <input name="next" type="hidden" value="/"/>
                  <input name="language" type="hidden" value="en"/>
                  <input name="next" type="hidden" value="{{ request.path|withoutLan }}"/>
                  <input type="submit" value="EN" class="btn btn-default"/>
                </form>
                <a>|</a>
                <form action="{% url 'set_language' %}" method="post">{% csrf_token %}
                  <input name="next" type="hidden" value="/"/>
                  <input name="language" type="hidden" value="tr"/>
                  <input name="next" type="hidden" value="{{ request.path|withoutLan }}"/>
                  <input type="submit" value="TR" class="btn btn-default"/>
                </form>
                <a href="{% url 'identity:login' %}">
                  {% trans "Login" %}
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="container">
        <div id="navbar" class="navbar navbar-default">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <div class="row">
              <div class="col-xs-12">
                <img src="/static/home/img/logo/csLogo.png" alt="" class="logo"/>
                <span href="{% url 'home:index' %}" class="lead title">
                  <a href="{% url 'home:index' %}">
                    <strong>
                      {% trans "Department of <br> Computer Science" %}
                    </strong>
                  </a>
                </span>
              </div>
            </div>
          </div>
          <div class="collapse navbar-collapse">
            <div class="row">
              <div class="col-xs-12">
                <ul class="nav navbar-nav navbar-right">
                  <li class="active">
                    <a href="{% url 'home:index' %}">
                      <i class="icon-home"></i>
                    </a>
                  </li>
                  <li>
                    <a href="{% url 'home:about' %}">
                      {% trans "About" %}
                    </a>
                  </li>
                  <li>
                    <a href="{% url 'home:people' %}">
                      {% trans "People" %}</a>
                  </li>
                  <li>
                    <a href="{% url 'home:programOverview' %}">
                      {% trans "Programs" %}
                    </a>
                  </li>
                  <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                      {% trans "Research" %}
                      <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                      <li>
                        <a href="{% url 'home:research' %}">
                          {% trans "Research Projects" %}
                        </a>
                      </li>
                      <li role="separator" class="divider"></li>
                      <li>
                        <a href="{% url 'home:researchGroup' %}">
                          {% trans "Research Groups" %}
                        </a>
                      </li>
                    </ul>
                  </li>
                  <li>
                    <a href="{% url 'home:newsEventsOVerview' %}">
                      {% trans "News" %}</a>
                  </li>
                  <li class="hidden-sm hidden-xs">
                    <p id="logo-university">
                      <a class="navbar-brand" href="http://sehir.edu.tr/"></a>
                    </p>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </header>
    <!--/#header-->
    {% block content %}
    {% endblock %}
    <section id="contact">
      <div class="container">
        <div class="box last">
          <div class="row">
            <div class="col-sm-6">
              <address>
                İstanbul Şehir University
                <br>
                Altunizade Mah. Oymacı Sok. No: 15
                <br>
                34660 Istanbul, Turkey
                <br>
                Email: <a href="mailto:cs@sehir.edu.tr">cs@sehir.edu.tr</a>
                <br>
                <abbr title="Phone">Phone:</abbr>
                (+90) 44 44 0 34
              </address>
            </div>
            <div class="col-sm-6">
              <div class="col-md-4">
                <a href="https://www.linkedin.com/groups/8456321" target="_blank">
                  <i class="icon-linkedin icon-social"></i>
                  Linkedin
                </a>
              </div>
              <div class="col-md-4">
                <a href="https://twitter.com/sehir_cs" target="_blank">
                  <i class="icon-twitter icon-social"></i>
                  Twitter
                </a>
              </div>
              <div class="col-md-4">
                <a href="https://www.youtube.com/channel/UCTAFsvpKz2IzTk4unPk2rbQ" target="_blank">
                  <i class="icon-youtube icon-social"></i>
                  Youtube
                </a>
              </div>
            </div>
          </div>
          <!--/.row-->
        </div>
        <!--/.box-->
      </div>
      <!--/.container-->
    </section>
    <!--/#contact-->
    <script src="/static/home/js/jquery.js"></script>
    <script src="/static/home/js/bootstrap.min.js"></script>
    <script src="/static/home/js/jquery.isotope.min.js"></script>
    <script src="/static/home/js/jquery.prettyPhoto.js"></script>
    <script src="/static/home/js/main.js"></script>
    {% block js %}
    {% endblock %}
    <script>
      (function(i, s, o, g, r, a, m) {
        i['GoogleAnalyticsObject'] = r;
        i[r] = i[r] || function() {
          (i[r].q = i[r].q || []).push(arguments)
        },
        i[r].l = 1 * new Date();
        a = s.createElement(o),
        m = s.getElementsByTagName(o)[0];
        a.async = 1;
        a.src = g;
        m.parentNode.insertBefore(a, m)
      })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

      ga('create', 'UA-71666019-1', 'auto');
      ga('send', 'pageview');
    </script>
  </body>

</html>

home/templates/index.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}
{% trans "Home" %}
{% endblock %}

{% block content %}

<section id="numbers">
  <div class="container">
    <div class="box">
      <div class="row">
        <div class="col-xs-12">
          <span class="label label-info">
            {% trans "CS in Numbers" %}
          </span>
        </div>
      </div>
      <div class="col-xs-12">
        {{ numbers.text|safe }}
      </div>
    </div>
  </div>
</section>

<section class="carousel" id="main-slider">
  <div class="container">
    <div class="box first">
      <div class="col-md-1 hidden-xs hidden-sm">
        <h2 class="rotatedText">
          {% trans "Research" %}
        </h2>
        <img class="bowknot" src="/static/home/img/or.png">
      </div>
      <div class="col-md-11 col-xs-12">
        <div class="carousel" data-ride="carousel" id="myCarousel">
          <div class="carousel-inner" role="listbox">
            {% for i in slider %}
            <div class="item">
              <a href="{% url 'home:research' %}#{{ i.title }}">
                <img alt="Chania" src="{{ MEDIA_URL }}{{ i.poster }}">
              </a>
            </div>
            {% endfor %}
          </div>
          <!-- Left and right controls -->
          <a class="left carousel-control" data-slide="prev" href="#myCarousel" role="button">
            <span aria-hidden="true" class="glyphicon glyphicon-chevron-left"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="right carousel-control" data-slide="next" href="#myCarousel" role="button">
            <span aria-hidden="true" class="glyphicon glyphicon-chevron-right"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
      </div>
    </div>
  </div>
</section>
<!--/#main-slider-->

<section id="about-us">
  <div class="container">
    <div class="box">
      <div class="col-md-1 hidden-xs hidden-sm">
        <img class="bowknot" src="/static/home/img/or.png">
        <h2 class="rotatedText">
          {% trans "Faculty" %}
        </h2>
      </div>
      <div class="col-md-11 col-xs-12">
        <div class="center">
          <h2 class="hidden-lg hidden-md">
            {% trans "Faculty" %}
          </h2>
        </div>
        <div class="carousel scale" id="team-scroller">
          <div class="carousel-inner">
            {% for i in faculty %}
            <div class="item">
              <div class="row">
                {% for j in i %}
                <div class="col-sm-4">
                  <div class="member">
                    <p>
                      <a href="{% url 'home:profile' j.id j.first_name j.last_name %}">
                        <img alt="" class="img-responsive img-thumbnail img-circle" src="{{ MEDIA_URL }}{{ j.image }}">
                      </a>
                    </p>
                    <h3>
                      <a href="{% url 'home:profile' j.id j.first_name j.last_name %}">
                        {{ j.first_name }}
                        {{ j.middle_name }}
                        {{ j.last_name }}
                      </a>
                      <small class="designation bold">
                        {% trans j.title %}

                        {% if j.visit %}
                          ({% trans "Visiting" %})
                        {% endif %}

                        {% if j.leave %}
                          ({% trans "On Leave" %})
                        {% endif %}

                        {% if j.chair %}
                          ({% trans "Chair" %})
                        {% endif %}
                      </small>
                      <small class="designation">{% trans "PhD" %},
                        {{ j.phd }}</small>
                    </h3>
                  </div>
                </div>
                {% endfor %}
              </div>
            </div>
            {% endfor %}
          </div>
          <a class="left-arrow" data-slide="prev" href="#team-scroller">
            <i class="icon-angle-left icon-4x"></i>
          </a>
          <a class="right-arrow" data-slide="next" href="#team-scroller">
            <i class="icon-angle-right icon-4x"></i>
          </a>
        </div>
        <!--/.carousel-->
      </div>
      <!--/.box-->
    </div>
  </div>
  <!--/.container-->
</section>
<!--/#about-us-->

<section id="portfolio">
  <div class="container">
    <div class="box">
      <div class="col-md-1 hidden-xs hidden-sm">
        <img class="bowknot" src="/static/home/img/or.png">
        <h2 class="rotatedText">{% trans "Programs" %}</h2>
      </div>
      <div class="col-md-11 col-xs-12">
        <div class="center gap">
          <h2 class="hidden-lg hidden-md">
            {% trans "Programs" %}
          </h2>
        </div>
        <!--/.center-->
        <div class="row"></div>
        <div class="row" id="pricing">
          {% for i in program %}
          <div class="col-md-4">
            <a href="{% url 'home:programOverview' %}#{{ i.title }}">
              <img alt="" class="img-responsive img-thumbnail" src="{{ MEDIA_URL }}{{ i.image }}">
              <div class="program-title">
                <h3>
                  {{ i.title }}
                </h3>
              </div>
            </a>
          </div>
          {% endfor %}
        </div>
        <!--/.row-->
      </div>
    </div>
    <!--/.box-->
  </div>
  <!--/.container-->
</section>
<!--/#portfolio-->
<section id="services">
  <div class="container">
    <div class="box">
      <div class="col-md-1 hidden-xs hidden-sm">
        <img class="bowknot" src="/static/home/img/or.png">
        <h2 class="rotatedText">
          {% trans "News" %}
        </h2>
      </div>
      <div class="col-md-11 col-xs-12">
        <div class="center">
          <h2 class="hidden-lg hidden-md">
            {% trans "News" %}
          </h2>
        </div>
        <div class="carousel scale" id="services-scroller">
          <div class="carousel-inner">
            {% for i in news %}
            <div class="item">
              <div class="row">
                {% for j in i %}
                <div class="col-md-4 col-sm-6">
                  <div class="center">
                    <a href="{% url 'home:newsEvent' j.id %}">
                      {% if j.poster %}
                      <img class="img-responsive img-thumbnail max-img-hei" src="{{ MEDIA_URL }}{{ j.poster }}"/>
                      {% endif %}
                      <h4>{{ j.title }}</h4>
                    </a>
                    <p>
                      {{ j.date }}
                    </p>
                    <p>
                      {{ j.description|striptags|slice:":180" }}...
                    </p>
                  </div>
                </div>
                <!--/.col-md-4-->
                {% endfor %}
              </div>
            </div>
            {% endfor %}
          </div>
          <a class="left-arrow" data-slide="prev" href="#services-scroller">
            <i class="icon-angle-left icon-4x"></i>
          </a>
          <a class="right-arrow" data-slide="next" href="#services-scroller">
            <i class="icon-angle-right icon-4x"></i>
          </a>
        </div>
      </div>
    </div>
    <!--/.box-->
  </div>
  <!--/.container-->
</section>
<!--/#services-->
<!--/#services-->

{% endblock %}
{% block js %}
<script src="/static/home/js/resizer.js"></script>
{% endblock %}

home/templates/newsEventsOverview.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}
{% trans "News and Events" %}
{% endblock %}

{% block content %}
<section id="news-overview">
  <div class="container">
    <div class="box first">
      <div class="center">
        <h3 class="small-gap">
          {% trans "News and Events" %}</h3>
        {% for i in news %}
        <div class="item">
          <div class="row">
            {% for j in i %}
            <div class="col-md-4 col-sm-6">
              <div class="center">
                <a href="{% url 'home:newsEvent' j.id %}">
                  {% if j.poster %}
                  <img src="{{ MEDIA_URL }}{{ j.poster }}" class="img-responsive img-thumbnail max-img-hei"/>
                {% else %}
                  <br>
                  <br>
                  {% endif %}
                  <h4>
                    {{ j.title }}
                  </h4>
                  <p>
                    {{ j.date }}
                  </p>
                  <p>{{ j.description|striptags|slice:":180" }}...</p>
                </a>
              </div>
            </div>
            <!--/.col-md-4-->
            {% endfor %}
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
    <!--/.box-->
  </div>
  <!--/.container-->
</section>
<!--/#portfolio-->
{% endblock %}